---
title: "Setup UKB project on Rosalind"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Setup UKB project on Rosalind}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE,
  echo = TRUE,
  message = FALSE
)
```

***

**Note. This document describes the setup of a UKB project on Rosalind for access with ukbkings.**

***

#### Setup a project directory

Navigate to /scratch/datasets/ukbiobank, create a project
directory usb\<*project_id*\>_\<*owner_name*\>, download and run
`project.py`. This script will create the project directory
structure in **Figure 1**, collect the data munging codebase, and
download the required UKB programs and utilites. Files used by the
data munging pipeline are stored in resources/ (UKB utilites: 
Codings_Showcase.csv, encoding.ukb, ukbunpack, ukbconv), src/ 
(munge_ukb.py, cluster.json), and log/.

```{bash}
cd /scratch/datasets/ukbiobank
mkdir ukb_<project_id>_<owner_name>
cd ukb_<project_id>_<owner_name>

wget https://raw.githubusercontent.com/kenhanscombe/ukbkings/master/project.py
chmod +x project.py

# Load Rosalind default python3 module
module load devtools/anaconda/2019.3-python3.7.3
./project.py
```

<br>

<p style="font-family:menlo; color:white; font-size:85%">
<span style="color:dodgerblue;">/scratch/datasets/ukbiobank/</span>  
||-- <span style="color:dodgerblue">ukb\<*project_id*\>_\<*owner_name*\>/</span>  
|| ||-- <span style="color:dodgerblue;">raw/</span>  
|| ||-- <span style="color:dodgerblue;">resources/</span>  
|| ||-- <span style="color:dodgerblue;">log/</span>  
|| ||-- <span style="color:dodgerblue;">src/</span>  
|| ||-- <span style="color:dodgerblue;">genotyped/</span>  
|| ||-- <span style="color:dodgerblue;">imputed/</span>  
|| ||-- <span style="color:dodgerblue;">phenotypes/</span>  
|| ||-- <span style="color:limegreen;">project.py</span>  
|| ||-- <span style="color:limegreen;">link.py</span>  
|| ||-- <span style="color:limegreen;">snake.py</span>  
|| ||-- <span style="color:dimgrey;">Snakefile</span>
</p>

**Figure 1** Project directory structure after running project.py

<br>

#### Include project data

The UKB project encrypted files (\*.enc) and associated key files
(\*.key), and withdrawal files (w\<*project-id*\>_\<*yyyymmdd*\>.csv)
must be copied into the subdirectory raw/. Change the key file names
to match the encrypted files: ukb\<*project_id*\>.enc pairs with
ukb\<*project_id*\>.key. The first line in each key file should be
the project id; the second line should be the decryption key.

Use the UKB program ukgene to download project-specific sample
information files (.fam and .sample) and relatedness file (*rel*.dat/.txt)
into raw/. If the key file for your genetic data is k\<*project_id*\>.key

```{bash}
cd raw

# fam
../resources/ukgene cal -c1 -m -ak<project_id>.key

# sample
../resources/ukgene imp c1 -m -ak<project_id>.key

# relatedness
../resources/ukgene rel -ak<project_id>.key
```

<br>

#### Munge the UKB data

Process the encrypted UKB files into formats to be read by ukbkings
and include symlinks to the shared UKB genotyped and imputed genetic
data on Rosalind.

```{bash}
./snake.py
```

The munged phenotype data  are stored in phenotypes/, the genetic 
symlinks in genotyped/ and imputed/, and output
information is written to log/ (**Figure 2**). For a dry run, in
which no files are edited/ written to disk, only details of what
would be munged is printed to standard output, use `./snake.py -n`

<br>

<p style="font-family:menlo; color:white; font-size:85%">
<span style="color:dodgerblue;">/scratch/datasets/ukbiobank/</span>  
||-- <span style="color:dodgerblue">ukb\<*project_id*\>_\<*owner_name*\>/</span>  
||-- ||-- <span style="color:dimgrey">\...</span>  
||-- ||-- <span style="color:dodgerblue">phenotypes/</span>  
||-- ||-- ||-- <span style="color:dimgrey">ukb\<dataset_id\>.csv</span>  
||-- ||-- ||-- <span style="color:dimgrey">ukb\<dataset_id\>.html</span>  
||-- ||-- ||-- <span style="color:dimgrey">ukb\<dataset_id\>_field_finder.text</span>  
||-- ||-- <span style="color:dodgerblue">genotyped/</span>  
||-- ||-- ||-- <span style="color:mediumturquoise">ukb\<project_id\>.bed</span>  
||-- ||-- ||-- <span style="color:mediumturquoise">ukb\<project_id\>.bim</span>  
||-- ||-- <span style="color:dodgerblue">imputed/</span>  
||-- ||-- ||-- <span style="color:mediumturquoise">ukb_sqc.txt</span>  
||-- ||-- ||-- <span style="color:mediumturquoise">ukb_sqc_fields.txt</span>  
||-- ||-- ||-- <span style="color:mediumturquoise">ukb_imp_chr\*.bgen</span>  
||-- ||-- ||-- <span style="color:mediumturquoise">ukb_imp_chr\*.bgen.bgi</span>  
||-- ||-- ||-- <span style="color:mediumturquoise">ukb_mfi_chr\*.txt</span>
</p>

**Figure 2** Phenotype data and genetic data symlinks

<br>

#### Add symlinks to sample information and relatedness files

Sample information files (.fam and .sample) and the relatedness file
(*rel*.dat/.txt) should be in raw/. Create symlinks to these project-specific
files in genotyped/ and imputed/ (**Figure 3**).

```{bash}
./link.py -f <path_to_fam_file> -s <path_to_sample_file> -r <path_to_relatedness_file>
```

You can link one or more of these files (they do not all need to be 
passed to the program).

<br>

<p style="font-family:menlo; color:white; font-size:85%">
<span style="color:dodgerblue;">/scratch/datasets/ukbiobank/</span>  
||-- <span style="color:dodgerblue">ukb\<*project_id*\>_\<*owner_name*\>/</span>  
||-- ||-- <span style="color:dimgrey">\...</span>  
||-- ||-- <span style="color:dodgerblue">genotyped/</span>  
||-- ||-- ||-- <span style="color:mediumturquoise">ukb\<project_id\>.fam</span>  
||-- ||-- <span style="color:dodgerblue">imputed/</span>  
||-- ||-- ||-- <span style="color:mediumturquoise">ukb\<project_id\>.sample</span>  
||-- ||-- ||-- <span style="color:mediumturquoise">ukb\<project_id\>.rel</span>
</p>

**Figure 3** Project-specific sample information and relatedness symlinks

<br>

**UKB genetic data resources:**

* [Accessing Genetic Data within UK Biobank](https://biobank.ctsu.ox.ac.uk/crystal/crystal/docs/ukbgene_instruct.html#aut)
* [Resource 531: Description of genetic data types](http://biobank.ndph.ox.ac.uk/showcase/refer.cgi?id=531)
* [Resource 664: Instructions for downloading genetic data using ukbgene](https://biobank.ctsu.ox.ac.uk/crystal/refer.cgi?id=664)
* [Resource 667: UK Biobank Keyfile](http://biobank.ndph.ox.ac.uk/showcase/refer.cgi?id=667)

<br>

#### Access the data with ukbkings

The data should now be available from anywhere on Rosalind through
the [ukbkings](https://kenhanscombe.github.io/ukbkings) R package. Read
[Access UKB data on Rosalind](https://kenhanscombe.github.io/ukbkings/articles/kcl-ukb-access.html)
for a detailed description of usage. The same usage documentation is
included in a package vignette. In R

```{R}
devtools::install_github("kenhanscombe/ukbkings", dependencies = TRUE, force = TRUE)
vignette("Access UKB data on Rosalind")
```

<br>

***

<br>

#### Additional withdrawals

Each time an updated set of participant withdrawals is received,
replace the w\<*project-id*\>_\<*yyyymmdd*\>.csv file in raw/ with
the new file. To exclude the latest withdrawals you have to generate
your dataset with ukbkings again. Be aware that if any researcher on
your project does run the tool again (to grab some other data say),
this would apply the latest set of withdrawals. 

<br>

#### Updates to phenotype data

If you receive any new data you would like to incorporate, place the
new .enc and .key files (prepared as described in [Include
project data]) into raw/ and re-run the data munging step
(described in [Munge the UKB data]).



